import htpy as h

from docs.components_base import API_BASE, code_block, code_tabs, ic, tip_box


def example_card(id_: str, icon: str, title: str, desc: str, *blocks: h.Node) -> h.Node:
    return h.div(".example-full-card", id=id_)[
        h.div(".example-card-header")[
            h.div(".example-card-icon")[icon],
            h.div[h.h3[title], h.p[desc]],
        ],
        h.div(".example-card-body")[blocks],
    ]


# ── Python snippets ───────────────────────────────────────────────────────────


def general_py() -> h.Node:
    return code_block(
        "general_search.py",
        "PY",
        [
            h.span(".kw")["from"],
            " blocket_api ",
            h.span(".kw")["import"],
            " ",
            h.span(".cls")["BlocketAPI"],
            "\n\n",
            "api ",
            h.span(".op")["="],
            " ",
            h.span(".cls")["BlocketAPI"],
            "()\n",
            "results ",
            h.span(".op")["="],
            " api.",
            h.span(".fn")["search"],
            "(",
            h.span(".str")['"Tamagotchi"'],
            ")\n\n",
            h.span(".kw")["for"],
            " item ",
            h.span(".kw")["in"],
            " results[",
            h.span(".str")['"docs"'],
            "]:\n",
            "    price ",
            h.span(".op")["="],
            " item.",
            h.span(".fn")["get"],
            "(",
            h.span(".str")['"price"'],
            ", {}).",
            h.span(".fn")["get"],
            "(",
            h.span(".str")['"amount"'],
            ", ",
            h.span(".str")['"N/A"'],
            ")\n",
            "    ",
            h.span(".fn")["print"],
            '(f"{item[',
            h.span(".str")['"heading"'],
            ']} — {price} SEK")',
        ],
    )


def general_curl() -> h.Node:
    return code_block(
        "terminal",
        "SH",
        [
            f'curl "{API_BASE}/v1/search?query=Tamagotchi&sort_order=PRICE_ASC"',
        ],
    )


def car_py() -> h.Node:
    return code_block(
        "car_filter.py",
        "PY",
        [
            h.span(".kw")["from"],
            " blocket_api ",
            h.span(".kw")["import"],
            " (\n",
            "    ",
            h.span(".cls")["BlocketAPI"],
            ", ",
            h.span(".cls")["CarModel"],
            ", ",
            h.span(".cls")["CarSortOrder"],
            ",\n",
            "    ",
            h.span(".cls")["CarTransmission"],
            ", ",
            h.span(".cls")["CarWheelDrive"],
            ", ",
            h.span(".cls")["Location"],
            ",\n)\n\n",
            "api ",
            h.span(".op")["="],
            " ",
            h.span(".cls")["BlocketAPI"],
            "()\n",
            "cars ",
            h.span(".op")["="],
            " api.",
            h.span(".fn")["search_car"],
            "(\n",
            "    models",
            h.span(".op")["="],
            "[",
            h.span(".cls")["CarModel"],
            ".",
            h.span(".var")["VOLVO"],
            "],\n",
            "    locations",
            h.span(".op")["="],
            "[",
            h.span(".cls")["Location"],
            ".",
            h.span(".var")["STOCKHOLM"],
            "],\n",
            "    transmissions",
            h.span(".op")["="],
            "[",
            h.span(".cls")["CarTransmission"],
            ".",
            h.span(".var")["AUTOMATIC"],
            "],\n",
            "    wheel_drive",
            h.span(".op")["="],
            "[",
            h.span(".cls")["CarWheelDrive"],
            ".",
            h.span(".var")["AWD"],
            "],\n",
            "    sort_order",
            h.span(".op")["="],
            h.span(".cls")["CarSortOrder"],
            ".",
            h.span(".var")["PRICE_ASC"],
            ",\n",
            "    price_to",
            h.span(".op")["="],
            h.span(".num")["200000"],
            ",\n",
            "    year_from",
            h.span(".op")["="],
            h.span(".num")["2018"],
            ",\n)\n\n",
            h.span(".fn")["print"],
            '(f"Found {len(cars[',
            h.span(".str")['"docs"'],
            '])} Volvos")',
        ],
    )


def car_curl() -> h.Node:
    return code_block(
        "terminal",
        "SH",
        [
            f'curl "{API_BASE}/v1/search/car?models=VOLVO&locations=STOCKHOLM',
            "&transmissions=AUTOMATIC&wheel_drive=AWD",
            '&price_to=200000&year_from=2018&sort_order=PRICE_ASC"',
        ],
    )


def alert_py() -> h.Node:
    return code_block(
        "price_alert.py",
        "PY",
        [
            h.span(".cmt")["# /// script"],
            "\n",
            h.span(".cmt")['# requires-python = ">=3.10"'],
            "\n",
            h.span(".cmt")['# dependencies = ["httpx"]'],
            "\n",
            h.span(".cmt")["# ///"],
            "\n\n",
            h.span(".kw")["import"],
            " httpx, json\n",
            h.span(".kw")["from"],
            " pathlib ",
            h.span(".kw")["import"],
            " Path\n\n",
            "QUERY, MAX_PRICE ",
            h.span(".op")["="],
            " ",
            h.span(".str")['"Sony WH-1000XM5"'],
            ", ",
            h.span(".num")["1800"],
            "\n",
            "SEEN ",
            h.span(".op")["="],
            " Path(",
            h.span(".str")['"seen.json"'],
            ")\n",
            "seen ",
            h.span(".op")["="],
            " ",
            h.span(".fn")["set"],
            "(json.",
            h.span(".fn")["loads"],
            "(SEEN.",
            h.span(".fn")["read_text"],
            "()) ",
            h.span(".kw")["if"],
            " SEEN.",
            h.span(".fn")["exists"],
            "() ",
            h.span(".kw")["else"],
            " [])\n\n",
            "docs ",
            h.span(".op")["="],
            " httpx.",
            h.span(".fn")["get"],
            "(\n",
            "    ",
            h.span(".str")[f'"{API_BASE}/v1/search"'],
            ",\n",
            "    params",
            h.span(".op")["="],
            "{",
            h.span(".str")['"query"'],
            ": QUERY, ",
            h.span(".str")['"sort_order"'],
            ": ",
            h.span(".str")['"PRICE_ASC"'],
            "},\n",
            ").",
            h.span(".fn")["json"],
            "()[",
            h.span(".str")['"docs"'],
            "]\n\n",
            h.span(".kw")["for"],
            " d ",
            h.span(".kw")["in"],
            " docs:\n",
            "    price ",
            h.span(".op")["="],
            " d.",
            h.span(".fn")["get"],
            "(",
            h.span(".str")['"price"'],
            ", {}).",
            h.span(".fn")["get"],
            "(",
            h.span(".str")['"amount"'],
            ", ",
            h.span(".num")["9e9"],
            ")\n",
            "    ",
            h.span(".kw")["if"],
            " price ",
            h.span(".op")["<="],
            " MAX_PRICE ",
            h.span(".kw")["and"],
            " d[",
            h.span(".str")['"id"'],
            "] ",
            h.span(".kw")["not in"],
            " seen:\n",
            "        ",
            h.span(".fn")["print"],
            "(f\"🔔 {d['heading']} — {price} SEK\")\n",
            "        seen.",
            h.span(".fn")["add"],
            "(d[",
            h.span(".str")['"id"'],
            "])\n\n",
            "SEEN.",
            h.span(".fn")["write_text"],
            "(json.",
            h.span(".fn")["dumps"],
            "(",
            h.span(".fn")["list"],
            "(seen)))\n\n",
            h.span(".cmt")["# */15 * * * * uv run price_alert.py"],
        ],
    )


def alert_curl() -> h.Node:
    return code_block(
        "terminal",
        "SH",
        [
            h.span(".cmt")["# Poll the REST API directly — no Python needed"],
            "\n",
            f'curl "{API_BASE}/v1/search?query=Sony+WH-1000XM5&sort_order=PRICE_ASC"',
            h.span(".cmt")["\n# pipe to jq to filter by price:\n"],
            f'curl -s "{API_BASE}/v1/search?query=Sony+WH-1000XM5&sort_order=PRICE_ASC"',
            " | jq '.docs[] | select(.price.amount <= 1800)'",
        ],
    )


def alert_run() -> h.Node:
    return code_block(
        "terminal",
        "SH",
        [
            "uv run price_alert.py\n",
            h.span(".cmt")["# 🔔 Sony WH-1000XM5 Like New — 1 750 SEK"],
        ],
    )


def csv_py() -> h.Node:
    return code_block(
        "to_csv.py",
        "PY",
        [
            h.span(".cmt")["# /// script"],
            "\n",
            h.span(".cmt")['# dependencies = ["blocket-api", "pandas"]'],
            "\n",
            h.span(".cmt")["# ///"],
            "\n\n",
            h.span(".kw")["import"],
            " pandas ",
            h.span(".kw")["as"],
            " pd\n",
            h.span(".kw")["from"],
            " blocket_api ",
            h.span(".kw")["import"],
            " ",
            h.span(".cls")["BlocketAPI"],
            ", ",
            h.span(".cls")["CarModel"],
            ", ",
            h.span(".cls")["CarSortOrder"],
            "\n\n",
            "api ",
            h.span(".op")["="],
            " ",
            h.span(".cls")["BlocketAPI"],
            "()\n",
            "raw ",
            h.span(".op")["="],
            " api.",
            h.span(".fn")["search_car"],
            "(\n",
            "    models",
            h.span(".op")["="],
            "[",
            h.span(".cls")["CarModel"],
            ".",
            h.span(".var")["TESLA"],
            "],\n",
            "    sort_order",
            h.span(".op")["="],
            h.span(".cls")["CarSortOrder"],
            ".",
            h.span(".var")["PRICE_ASC"],
            ",\n)\n\n",
            "rows ",
            h.span(".op")["="],
            " [{",
            h.span(".str")['"heading"'],
            ": d[",
            h.span(".str")['"heading"'],
            "], ",
            h.span(".str")['"price"'],
            ": d.",
            h.span(".fn")["get"],
            "(",
            h.span(".str")['"price"'],
            ", {}).",
            h.span(".fn")["get"],
            "(",
            h.span(".str")['"amount"'],
            ")} ",
            h.span(".kw")["for"],
            " d ",
            h.span(".kw")["in"],
            " raw[",
            h.span(".str")['"docs"'],
            "]]\n\n",
            "df ",
            h.span(".op")["="],
            " pd.",
            h.span(".cls")["DataFrame"],
            "(rows)\n",
            "df.",
            h.span(".fn")["to_csv"],
            "(",
            h.span(".str")['"tesla_prices.csv"'],
            ", index",
            h.span(".op")["="],
            h.span(".kw")["False"],
            ")\n",
            h.span(".fn")["print"],
            "(df.",
            h.span(".fn")["describe"],
            "()[",
            h.span(".str")['"price"'],
            "])",
        ],
    )


def csv_curl() -> h.Node:
    return code_block(
        "terminal",
        "SH",
        [
            h.span(".cmt")["# fetch JSON and convert to CSV with jq + awk"],
            "\n",
            f'curl -s "{API_BASE}/v1/search/car?models=TESLA&sort_order=PRICE_ASC"',
            " \\\n  | jq -r '.docs[] | [.heading, (.price.amount // \"\")] | @csv'",
        ],
    )


def paginate_py() -> h.Node:
    return code_block(
        "paginate.py",
        "PY",
        [
            h.span(".kw")["from"],
            " blocket_api ",
            h.span(".kw")["import"],
            " ",
            h.span(".cls")["BlocketAPI"],
            "\n\n",
            "api ",
            h.span(".op")["="],
            " ",
            h.span(".cls")["BlocketAPI"],
            "()\n",
            "all_results ",
            h.span(".op")["="],
            " []\n",
            h.span(".kw")["for"],
            " page ",
            h.span(".kw")["in"],
            " ",
            h.span(".fn")["range"],
            "(",
            h.span(".num")["5"],
            "):\n",
            "    batch ",
            h.span(".op")["="],
            " api.",
            h.span(".fn")["search"],
            "(",
            h.span(".str")['"MacBook"'],
            ", page",
            h.span(".op")["="],
            "page)[",
            h.span(".str")['"docs"'],
            "]\n",
            "    ",
            h.span(".kw")["if"],
            " ",
            h.span(".kw")["not"],
            " batch:\n        ",
            h.span(".kw")["break"],
            "\n",
            "    all_results.",
            h.span(".fn")["extend"],
            "(batch)\n\n",
            h.span(".fn")["print"],
            '(f"Fetched {len(all_results)} total listings")',
        ],
    )


def paginate_curl() -> h.Node:
    return code_block(
        "terminal",
        "SH",
        [
            h.span(".cmt")["# page parameter (1-based)"],
            "\n",
            f'curl "{API_BASE}/v1/search?query=MacBook&page=1"\n',
            f'curl "{API_BASE}/v1/search?query=MacBook&page=2"\n',
            f'curl "{API_BASE}/v1/search?query=MacBook&page=3"',
        ],
    )


def dealer_py() -> h.Node:
    return code_block(
        "dealer_stock.py",
        "PY",
        [
            h.span(".kw")["from"],
            " blocket_api ",
            h.span(".kw")["import"],
            " ",
            h.span(".cls")["BlocketAPI"],
            ", ",
            h.span(".cls")["CarSortOrder"],
            "\n\n",
            "api ",
            h.span(".op")["="],
            " ",
            h.span(".cls")["BlocketAPI"],
            "()\n",
            "dealer_cars ",
            h.span(".op")["="],
            " api.",
            h.span(".fn")["search_car"],
            "(\n",
            "    org_id",
            h.span(".op")["="],
            h.span(".str")['"12345"'],
            ",\n",
            "    sort_order",
            h.span(".op")["="],
            h.span(".cls")["CarSortOrder"],
            ".",
            h.span(".var")["PRICE_ASC"],
            ",\n)\n\n",
            h.span(".fn")["print"],
            '(f"Dealer has {len(dealer_cars[',
            h.span(".str")['"docs"'],
            '])} cars listed")',
        ],
    )


def dealer_curl() -> h.Node:
    return code_block(
        "terminal",
        "SH",
        [
            f'curl "{API_BASE}/v1/search/car?org_id=12345&sort_order=PRICE_ASC"',
        ],
    )


def boat_py() -> h.Node:
    return code_block(
        "boat_search.py",
        "PY",
        [
            h.span(".kw")["from"],
            " blocket_api ",
            h.span(".kw")["import"],
            " ",
            h.span(".cls")["BlocketAPI"],
            ", ",
            h.span(".cls")["Location"],
            "\n\n",
            "api ",
            h.span(".op")["="],
            " ",
            h.span(".cls")["BlocketAPI"],
            "()\n",
            "boats ",
            h.span(".op")["="],
            " api.",
            h.span(".fn")["search_boat"],
            "(\n",
            "    locations",
            h.span(".op")["="],
            "[",
            h.span(".cls")["Location"],
            ".",
            h.span(".var")["STOCKHOLM"],
            "],\n",
            "    price_to",
            h.span(".op")["="],
            h.span(".num")["200000"],
            ",\n)\n\n",
            h.span(".kw")["for"],
            " boat ",
            h.span(".kw")["in"],
            " boats[",
            h.span(".str")['"docs"'],
            "][:5]:\n",
            "    ",
            h.span(".fn")["print"],
            "(boat[",
            h.span(".str")['"heading"'],
            "], boat.",
            h.span(".fn")["get"],
            "(",
            h.span(".str")['"description"'],
            ", ",
            h.span(".str")['"—"'],
            ")[:80])",
        ],
    )


def boat_curl() -> h.Node:
    return code_block(
        "terminal",
        "SH",
        [
            f'curl "{API_BASE}/v1/search/boat?locations=STOCKHOLM&price_to=200000"',
        ],
    )


# ── Assembled cards ───────────────────────────────────────────────────────────


def cards() -> list[h.Node]:
    return [
        example_card(
            "general",
            "🔍",
            "General keyword search",
            "Search across all Blocket categories by keyword — electronics, furniture, clothing, and more.",
            code_tabs(("Python", general_py()), ("cURL", general_curl())),
        ),
        example_card(
            "car",
            "🚗",
            "Car search with filters",
            "Narrow down vehicles by model, transmission, wheel drive, price range, and year.",
            code_tabs(("Python", car_py()), ("cURL", car_curl())),
        ),
        example_card(
            "alert",
            "🔔",
            "Price alert script",
            "Monitor Blocket for deals below your target price. Remembers seen ads so you only get notified once.",
            code_tabs(("Python", alert_py()), ("cURL", alert_curl())),
            alert_run(),
            tip_box(
                "⚡",
                [
                    "Run with ",
                    ic("uv run price_alert.py"),
                    " — no virtualenv or install step needed.",
                ],
                kind="tip",
            ),
        ),
        example_card(
            "csv",
            "📊",
            "Export to CSV with pandas",
            "Pull search results into a DataFrame and export for analysis or charting.",
            code_tabs(("Python", csv_py()), ("cURL", csv_curl())),
            code_block("terminal", "SH", ["uv run to_csv.py"]),
        ),
        example_card(
            "paginate",
            "📄",
            "Paginate results",
            "Fetch more than 40 results by iterating over pages — useful for complete market scans.",
            code_tabs(("Python", paginate_py()), ("cURL", paginate_curl())),
        ),
        example_card(
            "dealer",
            "🏢",
            "Filter by dealer (org_id)",
            "Narrow results to a specific dealership — useful for monitoring a dealer's stock.",
            code_tabs(("Python", dealer_py()), ("cURL", dealer_curl())),
            tip_box(
                "💡",
                [
                    "Find an ",
                    ic("org_id"),
                    " by inspecting any dealer listing on Blocket.se — it's in the seller section.",
                ],
            ),
        ),
        example_card(
            "boat",
            "⛵",
            "Boat search",
            "Search for boats by location and price.",
            code_tabs(("Python", boat_py()), ("cURL", boat_curl())),
        ),
    ]
