[project]
name = "blocket_api"
version = "0.5.1"
description = "A python API wrapper for blocket.se"
authors = [{name = "dunderrrrrr", email = "emil.bjorkroth@gmail.com"}]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "httpx>=0.28.1",
    "beautifulsoup4>=4.14.3",
]

[project.optional-dependencies]
dev = [
    "pre-commit>=4.5.1",
    "pytest>=9.0.2",
    "respx>=0.22.0",
    "mypy>=1.19.1",
    "ruff>=0.9.0",
    "flask>=3.1.3",
    "htpy>=26.5.1",
    "gunicorn>=26.0.0",
]


[tool.pytest.ini_options]
testpaths = [
    "tests/*",
]
